apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

components:
- https://github.com/luccasa/apps.kustomize.lib//dev

labels:
- pairs:
    environment: development

patches:
- path: backend-workstation-gc.yaml