name: Lucca CI
run-name: >-
  ${{ github.ref_type == 'tag' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && format('🏷️ Release: {0}', github.ref_name)
    || github.event_name == 'pull_request' && format('👷 PR: {0}', github.event.pull_request.title)
    || github.event_name == 'push' && format('📌 Branch: {0}', github.ref_name)
    || format('🙈 {0} {1} {2}', github.event_name, github.ref_type, github.ref_name)
  }}
on:
  pull_request:
  workflow_dispatch:
    inputs: 
      runs-on:
        description: 'Which runner to use'
        default: 'lucca-ci-large'
        type: choice
        options:
          - lucca-ci
          - lucca-ci-large
          - ubuntu-latest
          - gh-hosted-small
          - gh-hosted-medium
      skip-sonar:
        description: 'Skip sonar analysis'
        default: false
        type: boolean
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  back:
    uses: LuccaSA/actions/.github/workflows/lucca-ci.yml@cf2e827cddc8c1f60672f26aa9d4de5cb4f87c6c # v2.0.2
    with:
      cake-file: back/build.cake
      mssql: true
      skip-sonar: ${{ github.event.inputs.skip-sonar == 'true' }}
      runs-on: ${{ github.event.inputs.runs-on || 'lucca-ci' }}
    secrets: inherit
  lint-swagger:
    uses: LuccaSA/actions/.github/workflows/lucca-ci.yml@cf2e827cddc8c1f60672f26aa9d4de5cb4f87c6c # v2.0.2
    with:
      cake-file: api/build.cake
      runs-on: ${{ github.event.inputs.runs-on || vars.CI_RUNNER || vars.DEFAULT_CI_RUNNER }} 
    secrets: inherit
  front:
    uses: LuccaSA/actions/.github/workflows/lucca-ci.yml@cf2e827cddc8c1f60672f26aa9d4de5cb4f87c6c # v2.0.2
    with:
      cake-file: front/build.cake
      runs-on: ${{ github.event.inputs.runs-on || vars.CI_RUNNER || vars.DEFAULT_CI_RUNNER  }}
    secrets: inherit
  docker:
    uses: LuccaSA/actions/.github/workflows/unified-docker-image.yml@cf2e827cddc8c1f60672f26aa9d4de5cb4f87c6c # v2.0.2
    needs:
      - front
      - back
    secrets: inherit
    with:
      applicationCode: paymonitor-expense-reports
      frontend: true
      docker-file: Dockerfile
      runs-on: lucca-ci
      image-name: paymonitor/paymonitor-expense-reports-unified